version: "3.8"

services:
  # MongoDB Service
  mongo_database:
    image: mongo:latest
    container_name: mongo_database
    ports:
      - "27017:27017" # Expose MongoDB on localhost
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: flight_system_db
    volumes:
      - ./data/mongodb:/data/db # Data volume for MongoDB persistence
      - ./data/config:/data/configdb # Config volume for MongoDB

  # Zookeeper Service
  zookeeper_server:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper_server
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181" # Expose Zookeeper on localhost
    volumes:
      - ./data/zookeeper:/var/lib/zookeeper # Persist Zookeeper data

  redis-db:
    container_name: redis-db
    command: valkey-server /usr/local/etc/valkey/valkey.conf --save 60 1 --loglevel warning
    image: valkey/valkey:7.2
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/valkey/valkey-data:/data
      - ./data/valkey/users_acl:/etc/valkey
      - ./data/valkey/valkey_conf:/usr/local/etc/valkey

  # Kafka Service
  kafka_broker:
    image: confluentinc/cp-kafka:latest
    container_name: kafka_broker
    depends_on:
      - zookeeper_server
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper_server:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka_broker:${KAFKA_INTERNAL_PORT},OUTSIDE://${KAFKA_HOST}:${KAFKA_EXTERNAL_PORT}
      KAFKA_LISTENERS: INTERNAL://kafka_broker:${KAFKA_INTERNAL_PORT},OUTSIDE://0.0.0.0:${KAFKA_EXTERNAL_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKAJS_NO_PARTITIONER_WARNING: 1
    ports:
      - "9092:9092" # Internal Kafka port
      - "9094:9094" # External Kafka port

# Volumes Configuration
volumes:
  mongodb:
  config:
  zookeeper:
